### ISSUE TITLE
Specify the version for gem dependencies

### ISSUE THREAD

**Issue by PGeffriaud** [rgcamus/dockerfile-alpine_smashing#3]
Hi,

I was wondering if it could be possible to specify which version of a gem we want to use as we can define it in the Gemfile of any smashing project.

For example, I would like to specify this dependency in this version in particular:
`gem 'nokogiri', '~> 1.6.8.rc2'`

It could be nice if we can define it directly in the command line to run the docker image
`docker run -e GEMS="nokogiri~>1.6.8.rc2"`

**Comment by rgcamus** [comment]
@PGeffriaud   You can change the install_gems  function, for this one:
```bash
function install_gems() {
  GEMS=$@
  IFS="|" read -a gems_array <<< "$GEMS"
  echo -e "\nInstalling gem(s): $GEMS"
  for GEM in "${gems_array[@]}"
  do
      echo -e "\ngem $GEM" >> Gemfile
  done
  bundle install
}
```
Can use multiple gems using  pipe "|" as a separator and Gemfile syntax. Example:

  $ docker run ... -e GEMS=" 'a_sample_gem', '~>1.1'   |   'another_gem' "  ...

See it in action in the [feature/gem_vers](https://github.com/rgcamus/dockerfile-alpine_smashing/tree/feature/gem_vers) branch
